vmware:
  host: "vc01.example.com"
  port: 443
  username: "administrator@vsphere.local"
  password: "your-secure-password"
  datacenter: "Datacenter01"
  cluster: "Cluster01"
  datastore: "Datastore01"
  network: "VM Network"
  folder: "/Datacenter01/vm/Workloads"

logging:
  level: "INFO"
  file: "workflow.log"